apiVersion: "benchmark.fission.io/v1"
kind: Config
metadata:
  name: big-response-workload-config
  namespace: fission-benchmark
spec:
  pairs:
  - function: big-response
    workload: simple-workload
  - function: big-response
    workload: medium-workload
  - function: big-response
    workload: heavy-workload
  functions:
  - name: big-response
    controls:
    - name: control1
      desc: a single node.js deployment behind k8s service
      endpoint: "http://127.0.0.1:31321/"
    - name: control2
      desc: 5 static replicas
      endpoint: "http://127.0.0.1:31322/"
  workloads:
  - name: simple-workload
    kind: warm # cold, warm
    number: 50
    concurrence: 2
    timeout: 60
    qps: 5
    verbose: false
    trigger:
      kind: Http
      spec:
        method: POST
        data: "{\"size\":2097152}" # 1024*1024*2
  - name: medium-workload
    kind: warm # cold, warm
    number: 200
    concurrence: 10
    timeout: 60
    qps: 60
    verbose: false
    trigger:
      kind: Http
      spec:
        method: POST
        data: "{\"size\":2097152}" # 1024*1024*2
  - name: heavy-workload
    kind: warm # cold, warm
    number: 5000
    concurrence: 250
    timeout: 60
    qps: 0
    verbose: false
    trigger:
      kind: Http
      spec:
        method: POST
        data: "{\"size\":2097152}" # 1024*1024*2
