apiVersion: v1
kind: Namespace
metadata:
  name: fission-benchmark
  labels:
    name: fission-benchmark

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cpu-intensive
  namespace: fission-benchmark
spec:
  replicas: 1
  template:
    metadata:
      labels:
        svc: cpu-intensive
    spec:
      containers:
      - name: server
        image: fission-benchmark/cpu-intensive:latest
        imagePullPolicy: IfNotPresent

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cpu-intensive-hpa
  namespace: fission-benchmark
spec:
  replicas: 1
  template:
    metadata:
      labels:
        svc: cpu-intensive-hpa
    spec:
      containers:
      - name: server
        image: fission-benchmark/cpu-intensive:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "500m"

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cpu-intensive-rep-5
  namespace: fission-benchmark
spec:
  replicas: 5
  template:
    metadata:
      labels:
        svc: cpu-intensive-rep-5
    spec:
      containers:
      - name: server
        image: fission-benchmark/cpu-intensive:latest
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: cpu-intensive
  namespace: fission-benchmark
  labels:
    svc: cpu-intensive
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8888
    nodePort: 31321
  selector:
    svc: cpu-intensive

---
apiVersion: v1
kind: Service
metadata:
  name: cpu-intensive-rep-5
  namespace: fission-benchmark
  labels:
    svc: cpu-intensive-rep-5
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8888
    nodePort: 31322
  selector:
    svc: cpu-intensive-rep-5

---
apiVersion: v1
kind: Service
metadata:
  name: cpu-intensive-hpa
  namespace: fission-benchmark
  labels:
    svc: cpu-intensive-hpa
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8888
    nodePort: 31323
  selector:
    svc: cpu-intensive-hpa

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-intensive-hpa
  namespace: fission-benchmark
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: cpu-intensive-hpa
  targetCPUUtilizationPercentage: 50