sudo: required
dist: trusty

language: go
go:
    - 1.8
    - tip

install:
   - go get github.com/Masterminds/glide

script:
   - cd ${TRAVIS_BUILD_DIR}
   - glide install
   - cd benchmark-bundle
   - go build
   - cd ${TRAVIS_BUILD_DIR}
   - hack/verify-gofmt.sh
   - go test -v -i $(go list ./... | grep -v '/vendor/' | grep -v 'examples/go')
   - go test -v $(go list ./... | grep -v '/vendor/' | grep -v 'examples/go')
