apiVersion: v1
kind: Namespace
metadata:
  name: fission-benchmark
  labels:
    name: fission-benchmark

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: big-response
  namespace: fission-benchmark
spec:
  replicas: 1
  template:
    metadata:
      labels:
        svc: big-response
    spec:
      containers:
      - name: server
        image: fission-benchmark/big-response:latest
        imagePullPolicy: IfNotPresent

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: big-response-rep-5
  namespace: fission-benchmark
spec:
  replicas: 5
  template:
    metadata:
      labels:
        svc: big-response-rep-5
    spec:
      containers:
      - name: server
        image: fission-benchmark/big-response:latest
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: big-response
  namespace: fission-benchmark
  labels:
    svc: big-response
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8888
    nodePort: 31321
  selector:
    svc: big-response

---
apiVersion: v1
kind: Service
metadata:
  name: big-response-rep-5
  namespace: fission-benchmark
  labels:
    svc: big-response-rep-5
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8888
    nodePort: 31322
  selector:
    svc: big-response-rep-5
