apiVersion: "benchmark.fission.io/v1"
kind: Config
metadata:
  name: helloworld-workload-config
  namespace: fission-benchmark
spec:
  pairs:
  - function: helloworld
    workload: simple-workload
  - function: helloworld
    workload: medium-workload
  - function: helloworld
    workload: heavy-workload
  functions:
  - name: helloworld
    controls:
    - name: control1
      desc: a single node.js deployment behind k8s service
      endpoint: "http://127.0.0.1:31321/"
    - name: control2
      desc: 5 replicas
      endpoint: "http://127.0.0.1:31322/"
  workloads:
  - name: simple-workload
    kind: warm # cold, warm
    number: 50
    concurrence: 2
    timeout: 60
    qps: 5
    verbose: false
    trigger:
      kind: Http
      spec:
        method: GET
        data: "nice"
  - name: medium-workload
    kind: warm # cold, warm
    number: 200
    concurrence: 10
    timeout: 60
    qps: 60
    verbose: false
    trigger:
      kind: Http
      spec:
        method: GET
        data: "nice"
  - name: heavy-workload
    kind: warm # cold, warm
    number: 10000
    concurrence: 300
    timeout: 60
    qps: 0
    verbose: false
    trigger:
      kind: Http
      spec:
        method: GET
        data: "nice"
