apiVersion: v1
kind: Namespace
metadata:
  name: fission-benchmark
  labels:
    name: fission-benchmark

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  namespace: fission-benchmark
spec:
  replicas: 1
  template:
    metadata:
      labels:
        svc: helloworld
    spec:
      containers:
      - name: server
        image: fission-benchmark/helloworld:latest
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: fission-benchmark
  labels:
    svc: helloworld
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8888
    nodePort: 31320
  selector:
    svc: helloworld