apiVersion: v1
kind: Namespace
metadata:
  name: fission-benchmark
  labels:
    name: fission-benchmark

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleep
  namespace: fission-benchmark
spec:
  replicas: 1
  template:
    metadata:
      labels:
        svc: sleep
    spec:
      containers:
      - name: server
        image: fission-benchmark/sleep:latest
        imagePullPolicy: IfNotPresent

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleep-rep-5
  namespace: fission-benchmark
spec:
  replicas: 5
  template:
    metadata:
      labels:
        svc: sleep-rep-5
    spec:
      containers:
      - name: server
        image: fission-benchmark/sleep:latest
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: sleep
  namespace: fission-benchmark
  labels:
    svc: sleep
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8888
    nodePort: 31321
  selector:
    svc: sleep

---
apiVersion: v1
kind: Service
metadata:
  name: sleep-rep-5
  namespace: fission-benchmark
  labels:
    svc: sleep-rep-5
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8888
    nodePort: 31322
  selector:
    svc: sleep-rep-5
